## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/network-test"
  to = "http://detectportal.firefox.com/success.txt"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/fake-router"
  to = "http://localhost:8001"
  status = 301
  force = true

[[redirects]]
  from = "/fake-route-200"
  to = "http://localhost:8001"
  status = 200
  force = true